-- The Soap Lab v0.3 Cloud Edition
-- Run this in Supabase SQL Editor.

create table if not exists inventory (
    id bigint generated by default as identity primary key,
    item_name text not null,
    category text,
    subcategory text,
    supplier text,
    quantity_purchased numeric default 0,
    unit text,
    total_cost numeric default 0,
    current_quantity numeric default 0,
    reorder_point numeric default 0,
    label_display_name text,
    notes text,
    created_at timestamptz default now()
);

create table if not exists fragrances (
    id bigint generated by default as identity primary key,
    fragrance_name text not null,
    supplier text,
    quantity_oz numeric default 0,
    total_cost numeric default 0,
    vanillin text,
    ifra_notes text,
    cp_notes text,
    strength_rating int default 3,
    overall_rating int default 3,
    notes text,
    created_at timestamptz default now()
);

create table if not exists recipes (
    id bigint generated by default as identity primary key,
    recipe_name text not null,
    product_type text,
    bars_made int default 1,
    retail_price numeric default 0,
    cure_days int default 42,
    notes text,
    created_at timestamptz default now()
);

create table if not exists recipe_lines (
    id bigint generated by default as identity primary key,
    recipe_id bigint references recipes(id) on delete cascade,
    inventory_id bigint references inventory(id) on delete restrict,
    amount_used numeric default 0,
    unit text,
    include_on_label boolean default true,
    label_name_override text,
    created_at timestamptz default now()
);

create table if not exists batches (
    id bigint generated by default as identity primary key,
    batch_number text,
    recipe_id bigint references recipes(id) on delete set null,
    date_made date,
    cure_date date,
    quantity_made int default 1,
    batch_cost numeric default 0,
    cost_per_item numeric default 0,
    notes text,
    created_at timestamptz default now()
);

create table if not exists finished_goods (
    id bigint generated by default as identity primary key,
    product_name text not null,
    product_type text,
    recipe_id bigint references recipes(id) on delete set null,
    batch_id bigint references batches(id) on delete set null,
    quantity_on_hand int default 0,
    cost_per_item numeric default 0,
    retail_price numeric default 0,
    notes text,
    created_at timestamptz default now()
);

create table if not exists sales (
    id bigint generated by default as identity primary key,
    sale_date date,
    channel text,
    product_name text,
    quantity_sold int default 1,
    sale_price_each numeric default 0,
    fees numeric default 0,
    shipping_material_cost numeric default 0,
    customer_name text,
    customer_email text,
    notes text,
    created_at timestamptz default now()
);

alter table inventory enable row level security;
alter table fragrances enable row level security;
alter table recipes enable row level security;
alter table recipe_lines enable row level security;
alter table batches enable row level security;
alter table finished_goods enable row level security;
alter table sales enable row level security;

create policy "Allow anon read inventory" on inventory for select using (true);
create policy "Allow anon insert inventory" on inventory for insert with check (true);
create policy "Allow anon update inventory" on inventory for update using (true);
create policy "Allow anon read fragrances" on fragrances for select using (true);
create policy "Allow anon insert fragrances" on fragrances for insert with check (true);
create policy "Allow anon read recipes" on recipes for select using (true);
create policy "Allow anon insert recipes" on recipes for insert with check (true);
create policy "Allow anon read recipe_lines" on recipe_lines for select using (true);
create policy "Allow anon insert recipe_lines" on recipe_lines for insert with check (true);
create policy "Allow anon read batches" on batches for select using (true);
create policy "Allow anon insert batches" on batches for insert with check (true);
create policy "Allow anon read finished_goods" on finished_goods for select using (true);
create policy "Allow anon insert finished_goods" on finished_goods for insert with check (true);
create policy "Allow anon read sales" on sales for select using (true);
create policy "Allow anon insert sales" on sales for insert with check (true);
